In [1]:
!uv add fastparquet

Resolved 110 packages in 1ms
Checked 13 packages in 4ms

In [20]:
import pandas as pd
url_trip="https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
df_trip = pd.read_parquet(url_trip, engine='fastparquet')
df_trip.head(20)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
5,1,2025-11-01 00:42:13,2025-11-01 01:04:50,N,1.0,112,48,2.0,5.10,26.8,...,1.5,6.55,0.0,NaN,1.0,39.35,1.0,1.0,2.75,0.75
6,2,2025-11-01 00:05:41,2025-11-01 00:39:20,N,1.0,83,87,1.0,9.80,43.6,...,0.5,9.92,0.0,NaN,1.0,59.52,1.0,1.0,2.75,0.75
7,2,2025-11-01 00:42:14,2025-11-01 01:13:20,N,1.0,66,233,1.0,5.01,28.9,...,0.5,6.98,0.0,NaN,1.0,41.88,1.0,1.0,2.75,0.75
8,2,2025-11-01 00:03:08,2025-11-01 00:06:27,N,1.0,223,223,1.0,0.63,5.1,...,0.5,1.52,0.0,NaN,1.0,9.12,1.0,1.0,0.00,0.00
9,2,2025-11-01 00:56:33,2025-11-01 01:01:34,N,1.0,130,130,1.0,1.15,7.9,...,0.5,0.00,0.0,NaN,1.0,10.40,2.0,1.0,0.00,0.00
10,2,2025-10-31 23:55:08,2025-11-01 00:25:30,N,1.0,41,234,1.0,5.30,31.7,...,0.5,4.00,0.0,NaN,1.0,41.70,1.0,1.0,2.75,0.75
11,2,2025-11-01 00:02:26,2025-11-01 00:02:31,N,5.0,93,93,1.0,0.00,28.0,...,0.0,5.80,0.0,NaN,1.0,34.80,1.0,2.0,0.00,0.00
12,2,2025-11-01 00:38:07,2025-11-01 00:44:51,N,5.0,92,192,2.0,1.13,15.0,...,0.0,0.00,0.0,NaN,1.0,16.00,1.0,2.0,0.00,0.00
13,2,2025-11-01 00:18:46,2025-11-01 00:30:40,N,1.0,243,152,1.0,3.73,18.4,...,0.5,4.18,0.0,NaN,1.0,25.08,1.0,1.0,0.00,0.00
14,2,2025-11-01 00:05:40,2025-11-01 00:05:45,N,5.0,244,244,1.0,0.00,9.5,...,0.0,2.10,0.0,NaN,1.0,12.60,1.0,2.0,0.00,0.00
15,2,2025-11-01 00:36:03,2025-11-01 01:16:11,N,4.0,82,265,1.0,21.68,110.8,...,0.5,0.00,0.0,NaN,1.0,113.30,2.0,1.0,0.00,0.00
16,2,2025-11-01 00:18:49,2025-11-01 00:40:58,N,1.0,255,209,2.0,4.40,24.0,...,0.5,2.00,0.0,NaN,1.0,32.00,1.0,1.0,2.75,0.75
17,2,2025-11-01 00:59:45,2025-11-01 01:09:06,N,1.0,256,255,1.0,0.46,9.3,...,0.5,2.36,0.0,NaN,1.0,14.16,1.0,1.0,0.00,0.00
18,1,2025-11-01 00:11:45,2025-11-01 00:20:03,Y,5.0,65,34,1.0,1.50,50.0,...,0.0,0.00,0.0,NaN,0.0,50.00,1.0,2.0,0.00,0.00
19,1,2025-11-01 00:57:43,2025-11-01 01:30:41,N,5.0,255,148,1.0,3.00,80.0,...,0.0,10.00,0.0,NaN,0.0,90.75,1.0,2.0,0.00,0.75

In [15]:
df_trip.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [16]:
df_trip.shape

(46912, 21)

In [17]:
df_trip.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='str')

In [18]:
df_zone=pd.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv")
df_zone.head(20)

    LocationID        Borough                     Zone service_zone
0            1            EWR           Newark Airport          EWR
1            2         Queens              Jamaica Bay    Boro Zone
2            3          Bronx  Allerton/Pelham Gardens    Boro Zone
3            4      Manhattan            Alphabet City  Yellow Zone
4            5  Staten Island            Arden Heights    Boro Zone
5            6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6            7         Queens                  Astoria    Boro Zone
7            8         Queens             Astoria Park    Boro Zone
8            9         Queens               Auburndale    Boro Zone
9           10         Queens             Baisley Park    Boro Zone
10          11       Brooklyn               Bath Beach    Boro Zone
11          12      Manhattan             Battery Park  Yellow Zone
12          13      Manhattan        Battery Park City  Yellow Zone
13          14       Brooklyn                Bay Ridge    Boro Zone
14          15         Queens  Bay Terrace/Fort Totten    Boro Zone
15          16         Queens                  Bayside    Boro Zone
16          17       Brooklyn                  Bedford    Boro Zone
17          18          Bronx             Bedford Park    Boro Zone
18          19         Queens                Bellerose    Boro Zone
19          20          Bronx                  Belmont    Boro Zone

In [7]:
df_zone.shape

(265, 4)

In [8]:
df_zone.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [9]:

november_trips = df_trip[
    (df_trip['lpep_pickup_datetime'] >= '2025-11-01') & 
    (df_trip['lpep_pickup_datetime'] < '2025-12-01')
]

# Count trips with distance <= 1 mile
short_trips = november_trips[november_trips['trip_distance'] <= 1]
count = len(short_trips)

print(f"Trips with distance ≤ 1 mile: {count}")

Trips with distance ≤ 1 mile: 8007

In [10]:
# Filter for November 18th, 2025 pickups
nov18_trips = df_trip[
    (df_trip['lpep_pickup_datetime'] >= '2025-11-18') & 
    (df_trip['lpep_pickup_datetime'] < '2025-11-19')
]

# Join with zone lookup to get pickup zone names
nov18_with_zones = nov18_trips.merge(
    df_zone[['LocationID', 'Zone']],
    left_on='PULocationID',  # Pickup LocationID column in trips
    right_on='LocationID',
    how='left'
)

# Sum total_amount by pickup zone
zone_totals = nov18_with_zones.groupby('Zone')['total_amount'].sum().reset_index()

# Find the zone with the highest total
top_zone = zone_totals.loc[zone_totals['total_amount'].idxmax()]

print(f"Pickup Zone: {top_zone['Zone']}")
print(f"Total Amount: ${top_zone['total_amount']:,.2f}")

Pickup Zone: East Harlem North
Total Amount: $9,281.92

In [11]:
 !uv add sqlalchemy psycopg2-binary

Resolved 110 packages in 1ms
Checked 13 packages in 0.31ms

In [32]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://firstroot:firstroot@localhost:5432/first_ny_taxi')

In [33]:
print(pd.io.sql.get_schema(df_trip, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [34]:
print(pd.io.sql.get_schema(df_zone, name='taxi_zone_lookup', con=engine))

CREATE TABLE taxi_zone_lookup (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [36]:
df_trip.head(n=0).to_sql(name='green_taxi_data', con=engine, if_exists='replace')

0

In [37]:
df_zone.head(n=0).to_sql(name='taxi_zone_lookup', con=engine, if_exists='replace')

0

In [39]:
!uv add tqdm

Resolved 122 packages in 2.75s
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 149ms
 + tqdm==4.67.3

In [40]:
from tqdm.auto import tqdm

In [41]:
df_trip = pd.read_parquet(url_trip)

In [56]:
from tqdm.auto import tqdm

chunk_size = 10000

for start in tqdm(range(0, len(df_trip), chunk_size)):
    end = start + chunk_size

    df_chunk = df_trip.iloc[start:end]

    df_chunk.to_sql(
        name='green_taxi_data',
        con=engine,
        if_exists='replace',
        index=False
    )

  0%|          | 0/5 [00:00<?, ?it/s]

In [62]:
zone_chunk_size = 100

for start in tqdm(range(0, len(df_zone), zone_chunk_size)):
    end = start + zone_chunk_size

    df_chunk_z = df_zone.iloc[start:end]

    df_chunk_z.to_sql(
        name='taxi_zone_lookup',
        con=engine,
        if_exists='append' if start > 0 else 'replace',
        index=False
    )

  0%|          | 0/3 [00:00<?, ?it/s]